import type { DesignRecipe, FeedbackOption } from './types'

export const recipes: DesignRecipe[] = [
  {
    id: 'cover-source-cluster',
    version: 'cover-source-cluster.v1',
    label: 'Cover Source Cluster',
    staffLabel: '표지에 넣기 좋은 대표 소스',
    description: '표지/포스터에 얹을 수 있는 정돈된 독립 그래픽으로 만듭니다.',
    useCase: '표지/포스터용 소스',
    composition: '중앙 메인 요소 1개 + 보조 요소 2~3개',
    style: '깔끔한 상업 일러스트',
    output: '투명 PNG 독립 소스',
    triggers: ['표지', '포스터', '책자', '보고서', '리플렛', '홍보물', '소스'],
    rules: [
      'Create a standalone cover design asset, not a complete poster.',
      'Use one clear main subject and two or three simplified supporting elements.',
      'Keep the silhouette readable and the composition balanced for layout placement.',
      'No background scenery, no sky, no ground plane, no text.',
    ],
    avoid: ['full poster layout', 'busy scenery', 'tiny scattered objects', 'letters', 'logo', 'watermark'],
  },
  {
    id: 'explain-infographic',
    version: 'explain-infographic.v1',
    label: 'Explainer Infographic Asset',
    staffLabel: '여러 내용을 한눈에 정리한 설명형 소스',
    description: '여러 소재를 분리해서 읽히게 정리하는 설명형 소스입니다.',
    useCase: '설명/인포그래픽형',
    composition: '요소 분리형, 시각적 그룹 구성',
    style: '간단한 벡터 인포그래픽',
    output: '투명 PNG 설명 소스',
    triggers: ['과정', '단계', '설명', '안내', '구성', '비교', '인포', '여러', '농기계', '바구니'],
    rules: [
      'Create a clean infographic-style asset with separated visual elements.',
      'Each element must be easy to recognize at a glance.',
      'Use simple shapes, consistent proportions, and clear spacing.',
      'No labels, no captions, no complete poster layout.',
    ],
    avoid: ['realistic scene', 'dense illustration', 'background landscape', 'text labels', 'chart text'],
  },
  {
    id: 'mascot-main',
    version: 'mascot-main.v1',
    label: 'Mascot Main Asset',
    staffLabel: '친근한 캐릭터 중심 소스',
    description: '사람이나 동물을 메인 캐릭터로 잡고 주변 요소는 보조로 줄입니다.',
    useCase: '캐릭터/마스코트',
    composition: '캐릭터 메인, 보조 소재 축약',
    style: '친근한 브랜드 마스코트',
    output: '투명 PNG 캐릭터 소스',
    triggers: ['캐릭터', '마스코트', '귀엽', '친근', '어린이', '가족', '농부', '사람'],
    rules: [
      'Create a friendly commercial mascot character as the main subject.',
      'Supporting objects should be smaller and simpler than the character.',
      'Use rounded shapes and a professional friendly expression.',
      'Avoid childish toy-like appearance unless explicitly requested.',
    ],
    avoid: ['scary face', 'overly childish', 'realistic portrait', 'complex background', 'brand logo'],
  },
  {
    id: 'signage-bold',
    version: 'signage-bold.v1',
    label: 'Bold Signage Asset',
    staffLabel: '간판/현수막에 크게 보이는 소스',
    description: '멀리서도 읽히는 큰 실루엣과 단순한 형태를 우선합니다.',
    useCase: '간판/현수막용 소스',
    composition: '큰 단일 실루엣 중심',
    style: '강한 외곽선의 단순 상업 그래픽',
    output: '투명 PNG 대형 출력 소스',
    triggers: ['간판', '현수막', '배너', '멀리', '크게', '입간판'],
    rules: [
      'Create a bold readable asset for signage and banners.',
      'Use a large simple silhouette with minimal small details.',
      'Keep contrast strong and edges clean for large-format printing.',
      'Do not include many small objects.',
    ],
    avoid: ['thin lines', 'small details', 'muted low contrast', 'busy composition', 'background'],
  },
  {
    id: 'single-object',
    version: 'single-object.v1',
    label: 'Single Object Cutout',
    staffLabel: '배경 없는 단일 오브젝트 소스',
    description: '하나의 물건이나 소재를 깨끗한 독립 소스로 만듭니다.',
    useCase: '오브젝트 단품형',
    composition: '단일 오브젝트 중앙 배치',
    style: '깨끗한 제품형 일러스트',
    output: '투명 PNG 오브젝트',
    triggers: ['오브젝트', '단품', '제품', '채소', '기계', '농기구', '소품'],
    rules: [
      'Create one isolated object asset centered in the frame.',
      'Use clean edges and simplified commercial illustration details.',
      'Keep generous transparent padding around the object.',
      'No scene, no supporting background objects.',
    ],
    avoid: ['environment', 'group scene', 'background', 'text', 'logo', 'shadowed floor'],
  },
  {
    id: 'icon-set',
    version: 'icon-set.v1',
    label: 'Icon Set Asset',
    staffLabel: '아이콘/픽토그램 세트',
    description: '여러 요소를 같은 규칙의 작은 아이콘 세트처럼 정리합니다.',
    useCase: '아이콘/픽토그램',
    composition: '균일한 크기의 요소 세트',
    style: '단순 픽토그램/아이콘',
    output: '투명 PNG 아이콘 세트',
    triggers: ['아이콘', '픽토그램', '세트', '표시', '분류'],
    rules: [
      'Create a consistent icon set with uniform scale and visual weight.',
      'Use simple shapes, clear outlines, and minimal color complexity.',
      'Place elements in an orderly grid-like arrangement without text.',
      'Keep every icon recognizable at small sizes.',
    ],
    avoid: ['realistic illustration', 'uneven scale', 'complex texture', 'labels', 'background'],
  },
]

export const feedbackOptions: FeedbackOption[] = [
  { id: 'usable', label: '쓸만함', kind: 'success' },
  { id: 'has-background', label: '배경이 생김', kind: 'failure' },
  { id: 'too-complex', label: '너무 복잡함', kind: 'failure' },
  { id: 'wrong-asset', label: '원하는 소스가 아님', kind: 'failure' },
  { id: 'text-or-logo', label: '글자/로고가 들어감', kind: 'failure' },
  { id: 'missing-elements', label: '요소가 빠짐', kind: 'failure' },
  { id: 'wrong-style', label: '스타일이 안 맞음', kind: 'failure' },
  { id: 'bad-composition', label: '구도가 별로임', kind: 'failure' },
]
